// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDyI2dwKbQzbMUTnb_tDFOKzL2hNHFlU4',
    appId: '1:975116680869:web:b8c712b42504681c5a174c',
    messagingSenderId: '975116680869',
    projectId: 'barber-app-fc234',
    authDomain: 'barber-app-fc234.firebaseapp.com',
    storageBucket: 'barber-app-fc234.firebasestorage.app',
    measurementId: 'G-XSECK05BRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzcxtNozMJ2teQnqli9qwaL1SbbDX6faE',
    appId: '1:975116680869:android:20c6e3927d8ead0f5a174c',
    messagingSenderId: '975116680869',
    projectId: 'barber-app-fc234',
    storageBucket: 'barber-app-fc234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDT9YRxG89efnCh_cLHj0j0Flx1QLybwI',
    appId: '1:975116680869:ios:de1bc6aeedb808a65a174c',
    messagingSenderId: '975116680869',
    projectId: 'barber-app-fc234',
    storageBucket: 'barber-app-fc234.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

}